using System.Collections.Frozen;
using System.Reflection;
using System.Text.RegularExpressions;
using CoreFoundry.Domain.Common;

namespace CoreFoundry.Domain.Schema;

/// <summary>
/// Rules for table and column names. The schema engine puts these names into DDL, so this check is
/// what makes that safe: a name that passes can only contain <c>[a-z0-9_]</c> and is never a keyword.
/// </summary>
public static partial class IdentifierRules
{
    /// <summary>MySQL's identifier limit.</summary>
    public const int MaxLength = 64;

    /// <summary>Prefix reserved for CoreFoundry's own objects.</summary>
    public const string ReservedPrefix = "cf_";

    /// <summary>Name of the primary key CoreFoundry adds to every table.</summary>
    public const string SystemColumnName = "id";

    private static readonly FrozenSet<string> ReservedWords = LoadReservedWords();

    /// <summary>
    /// Returns the name trimmed and in lower case (names are case-insensitive, so <c>Books</c> and
    /// <c>books</c> are the same name).
    /// </summary>
    /// <param name="what">"Table name" or "Column name", used in error messages.</param>
    /// <exception cref="DomainException">The name isn't allowed; the message says why (<see cref="DomainException.Field"/> is <c>name</c>).</exception>
    public static string Normalize(string? name, string what)
    {
        if (string.IsNullOrWhiteSpace(name))
        {
            throw Invalid($"{what} is required.");
        }

        var normalized = name.Trim().ToLowerInvariant();
        if (normalized.Length > MaxLength)
        {
            throw Invalid($"{what} must be at most {MaxLength} characters.");
        }

        if (!Pattern().IsMatch(normalized))
        {
            throw Invalid(
                $"{what} must start with a letter and contain only letters, digits and underscores.");
        }

        if (normalized == SystemColumnName)
        {
            throw Invalid($"\"{SystemColumnName}\" is reserved for the primary key CoreFoundry adds to every table.");
        }

        if (normalized.StartsWith(ReservedPrefix, StringComparison.Ordinal))
        {
            throw Invalid($"Names starting with \"{ReservedPrefix}\" are reserved by CoreFoundry.");
        }

        if (IsReservedWord(normalized))
        {
            throw Invalid($"\"{normalized}\" is a reserved word in MySQL.");
        }

        return normalized;
    }

    /// <summary>True if <paramref name="name"/> (lower case) is a MySQL reserved word.</summary>
    public static bool IsReservedWord(string name) => ReservedWords.Contains(name);

    private static DomainException Invalid(string message) => new(message) { Field = "name" };

    [GeneratedRegex("^[a-z][a-z0-9_]{0,63}$", RegexOptions.CultureInvariant)]
    private static partial Regex Pattern();

    // Generated by db/reserved-words.sql from INFORMATION_SCHEMA.KEYWORDS.
    private static FrozenSet<string> LoadReservedWords()
    {
        using var stream = Assembly.GetExecutingAssembly().GetManifestResourceStream("CoreFoundry.Domain.Schema.mysql-reserved-words.txt")
            ?? throw new InvalidOperationException("The reserved-word list is missing from the Domain assembly.");
        using var reader = new StreamReader(stream);

        var words = new List<string>();
        while (reader.ReadLine() is { } line)
        {
            if (line.Trim() is { Length: > 0 } word)
            {
                words.Add(word.ToLowerInvariant());
            }
        }

        return words.Count > 0
            ? words.ToFrozenSet(StringComparer.Ordinal)
            : throw new InvalidOperationException("The reserved-word list is empty.");
    }
}
