using System.Text;
using CoreFoundry.Application.Export;
using CoreFoundry.Domain.Schema;
using CoreFoundry.Domain.SchemaEngine;
using CoreFoundry.Infrastructure.Engine;

namespace CoreFoundry.Infrastructure.Export;

/// <summary>
/// The EF Core <c>InitialCreate</c> migration, its designer file and the model snapshot of an exported
/// backend, written the way <c>dotnet ef migrations add</c> writes them for MySql.EntityFrameworkCore.
/// The export test checks them with <c>dotnet ef migrations has-pending-model-changes</c>, so the
/// snapshot must describe exactly the model the entity configurations build.
/// </summary>
internal static class EfMigrationWriter
{
    public const string ProductVersion = "10.0.12";

    public static IEnumerable<GeneratedFile> For(ExportModel model)
    {
        ArgumentNullException.ThrowIfNull(model);
        var n = model.Solution;
        var tables = Tables(model);
        var folder = $"src/{n}.Infrastructure/Persistence/Migrations";
        var buildModel = BuildModel(n, tables);

        yield return new($"{folder}/{model.MigrationId}.cs", Migration(n, tables));
        yield return new($"{folder}/{model.MigrationId}.Designer.cs", $$"""
            // <auto-generated />
            using System;
            using {{n}}.Infrastructure.Persistence;
            using Microsoft.EntityFrameworkCore;
            using Microsoft.EntityFrameworkCore.Infrastructure;
            using Microsoft.EntityFrameworkCore.Migrations;
            using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

            #nullable disable

            namespace {{n}}.Infrastructure.Persistence.Migrations
            {
                [DbContext(typeof(AppDbContext))]
                [Migration("{{model.MigrationId}}")]
                partial class InitialCreate
                {
                    /// <inheritdoc />
                    protected override void BuildTargetModel(ModelBuilder modelBuilder)
                    {
            {{buildModel}}
                    }
                }
            }

            """);
        yield return new($"{folder}/AppDbContextModelSnapshot.cs", $$"""
            // <auto-generated />
            using System;
            using {{n}}.Infrastructure.Persistence;
            using Microsoft.EntityFrameworkCore;
            using Microsoft.EntityFrameworkCore.Infrastructure;
            using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

            #nullable disable

            namespace {{n}}.Infrastructure.Persistence.Migrations
            {
                [DbContext(typeof(AppDbContext))]
                partial class AppDbContextModelSnapshot : ModelSnapshot
                {
                    protected override void BuildModel(ModelBuilder modelBuilder)
                    {
            {{buildModel}}
                    }
                }
            }

            """);
    }

    // ---- The model, as the migration files see it ----

    private sealed record Column(
        string Property, string Name, string ClrType, bool IsValueType, string StoreType, int? MaxLength, int? Precision, int? Scale,
        bool Nullable, string? DefaultSql);

    private sealed record ForeignKey(string Property, string Column, string TargetTable, string TargetType, string Navigation, string OnDelete, bool Required, string Name);

    private sealed record Table(string Name, string TypeName, IReadOnlyList<Column> Columns, IReadOnlyList<(string Property, string Column, string Name, bool Unique)> Indexes, IReadOnlyList<ForeignKey> ForeignKeys);

    private static List<Table> Tables(ExportModel model)
    {
        var n = model.Solution;
        var tables = new List<Table>
        {
            new("cf_users", $"{n}.Domain.Entities.AppUser",
            [
                new("CreatedAt", "created_at", "DateTime", true, "datetime(6)", null, null, null, false, null),
                new("Email", "email", "string", false, "varchar(254)", 254, null, null, false, null),
                new("PasswordHash", "password_hash", "string", false, "varchar(255)", 255, null, null, false, null),
                new("Role", "role", "string", false, "varchar(16)", 16, null, null, false, null),
            ],
            [("Email", "email", "uq_cf_users_email", true)],
            []),
        };

        foreach (var entity in model.Entities)
        {
            var columns = entity.Properties.Select(property => new Column(
                property.Name,
                property.Column,
                CSharp.ClrType(property.Type),
                CSharp.ClrType(property.Type) != "string",
                StoreType(property.Type),
                property.Type.DataType == DataType.Varchar ? property.Type.Length : null,
                property.Type.DataType == DataType.Decimal ? property.Type.Precision : null,
                property.Type.DataType == DataType.Decimal ? property.Type.Scale : null,
                property.IsNullable,
                property.Default is { } value ? MySqlSqlRenderer.DefaultSql(value) : null)).ToList();

            var indexes = entity.Properties.Where(property => property.IsUnique)
                .Select(property => (property.Name, property.Column, entity.UniqueKeyName(property), true))
                .Concat(entity.Properties.Where(property => property.Reference is not null && !property.IsUnique)
                    .Select(property => (property.Name, property.Column, property.Reference!.ConstraintName, false)))
                .ToList();

            var foreignKeys = entity.Properties.Where(property => property.Reference is not null).Select(property =>
            {
                var reference = property.Reference!;
                var target = model.Entity(reference.TargetTable);
                return new ForeignKey(
                    property.Name, property.Column, reference.TargetTable, $"{n}.Domain.Entities.{target.ClassName}", reference.Navigation,
                    reference.OnDelete switch { ReferenceAction.Cascade => "Cascade", ReferenceAction.SetNull => "SetNull", _ => "Restrict" },
                    !property.IsNullable, reference.ConstraintName);
            }).ToList();

            tables.Add(new Table(entity.Table, $"{n}.Domain.Entities.{entity.ClassName}", columns, indexes, foreignKeys));
        }

        return tables;
    }

    private static string StoreType(ColumnType type) => type.DataType switch
    {
        DataType.Int => "int",
        DataType.BigInt => "bigint",
        DataType.Decimal => $"decimal({type.Precision},{type.Scale})",
        DataType.Bool => "tinyint(1)",
        DataType.Varchar => $"varchar({type.Length})",
        DataType.Text => "text",
        DataType.DateTime => "datetime(6)",
        DataType.Date => "date",
        DataType.Uuid => "char(36)",
        DataType.Json => "json",
        _ => throw new ArgumentOutOfRangeException(nameof(type), type, "Unknown type."),
    };

    // ---- InitialCreate.cs ----

    private static string Migration(string n, List<Table> tables)
    {
        var up = new List<string> { "migrationBuilder.AlterDatabase()\n    .Annotation(\"MySQL:Charset\", \"utf8mb4\");" };

        // Tables first, foreign keys after: references between tables (even in a cycle) then always work.
        foreach (var table in tables)
        {
            var columns = new List<string>
            {
                "id = table.Column<long>(type: \"bigint\", nullable: false)\n    .Annotation(\"MySQL:ValueGenerationStrategy\", MySQLValueGenerationStrategy.IdentityColumn)",
            };
            columns.AddRange(table.Columns.Select(column =>
            {
                var arguments = new List<string> { $"type: {CSharp.String(column.StoreType)}" };
                if (column.MaxLength is { } maxLength)
                {
                    arguments.Add($"maxLength: {maxLength}");
                }

                if (column.Precision is { } precision)
                {
                    arguments.Add($"precision: {precision}, scale: {column.Scale}");
                }

                arguments.Add($"nullable: {(column.Nullable ? "true" : "false")}");
                if (column.DefaultSql is { } defaultSql)
                {
                    arguments.Add($"defaultValueSql: {CSharp.String(defaultSql)}");
                }

                return $"{Member(column.Name)} = table.Column<{column.ClrType}>({string.Join(", ", arguments)})";
            }));

            up.Add(
                $"migrationBuilder.CreateTable(\n" +
                $"    name: {CSharp.String(table.Name)},\n" +
                $"    columns: table => new\n" +
                $"    {{\n" +
                $"{CSharp.Lines([string.Join(",\n", columns)], 8)}\n" +
                $"    }},\n" +
                $"    constraints: table =>\n" +
                $"    {{\n" +
                $"        table.PrimaryKey({CSharp.String(PrimaryKeyName(table.Name))}, x => x.id);\n" +
                $"    }})\n" +
                $"    .Annotation(\"MySQL:Charset\", \"utf8mb4\");");
        }

        foreach (var table in tables)
        {
            foreach (var index in table.Indexes)
            {
                up.Add(
                    $"migrationBuilder.CreateIndex(\n" +
                    $"    name: {CSharp.String(index.Name)},\n" +
                    $"    table: {CSharp.String(table.Name)},\n" +
                    $"    column: {CSharp.String(index.Column)}" + (index.Unique ? ",\n    unique: true);" : ");"));
            }
        }

        foreach (var table in tables)
        {
            foreach (var key in table.ForeignKeys)
            {
                up.Add(
                    $"migrationBuilder.AddForeignKey(\n" +
                    $"    name: {CSharp.String(key.Name)},\n" +
                    $"    table: {CSharp.String(table.Name)},\n" +
                    $"    column: {CSharp.String(key.Column)},\n" +
                    $"    principalTable: {CSharp.String(key.TargetTable)},\n" +
                    $"    principalColumn: \"id\",\n" +
                    $"    onDelete: ReferentialAction.{key.OnDelete});");
            }
        }

        var down = tables.SelectMany(table => table.ForeignKeys.Select(key =>
                $"migrationBuilder.DropForeignKey(\n    name: {CSharp.String(key.Name)},\n    table: {CSharp.String(table.Name)});"))
            .Concat(tables.AsEnumerable().Reverse().Select(table => $"migrationBuilder.DropTable(\n    name: {CSharp.String(table.Name)});"));

        return $$"""
            using System;
            using Microsoft.EntityFrameworkCore.Migrations;
            using MySql.EntityFrameworkCore.Metadata;

            #nullable disable

            namespace {{n}}.Infrastructure.Persistence.Migrations
            {
                /// <inheritdoc />
                public partial class InitialCreate : Migration
                {
                    /// <inheritdoc />
                    protected override void Up(MigrationBuilder migrationBuilder)
                    {
            {{CSharp.Lines(CSharp.Separated(up), 12)}}
                    }

                    /// <inheritdoc />
                    protected override void Down(MigrationBuilder migrationBuilder)
                    {
            {{CSharp.Lines(CSharp.Separated(down), 12)}}
                    }
                }
            }

            """;
    }

    /// <summary>MySQL ignores a primary key's name, but it must still fit 64 characters.</summary>
    private static string PrimaryKeyName(string table) => ("PK_" + table) is { Length: > Identifier.MaxLength } name ? name[..Identifier.MaxLength] : "PK_" + table;

    /// <summary>A column name as an anonymous-type member: C# keywords need an '@'.</summary>
    private static string Member(string column) => Keywords.Contains(column) ? "@" + column : column;

    // ---- BuildModel (designer and snapshot) ----

    private static string BuildModel(string n, List<Table> tables)
    {
        var blocks = new List<string>
        {
            "modelBuilder\n" +
            $"    .HasAnnotation(\"ProductVersion\", \"{ProductVersion}\")\n" +
            "    .HasAnnotation(\"Relational:MaxIdentifierLength\", 64);",
        };

        foreach (var table in tables.OrderBy(table => table.TypeName, StringComparer.Ordinal))
        {
            var lines = new List<string> { "b.Property<long>(\"Id\")\n    .ValueGeneratedOnAdd()\n    .HasColumnType(\"bigint\")\n    .HasColumnName(\"id\");" };
            foreach (var column in table.Columns.OrderBy(column => column.Property, StringComparer.Ordinal))
            {
                var builder = new StringBuilder($"b.Property<{column.ClrType}{(column.IsValueType && column.Nullable ? "?" : "")}>({CSharp.String(column.Property)})");
                if (!column.IsValueType && !column.Nullable)
                {
                    builder.Append("\n    .IsRequired()");
                }

                if (column.DefaultSql is not null)
                {
                    builder.Append("\n    .ValueGeneratedOnAdd()");
                }

                if (column.MaxLength is { } maxLength)
                {
                    builder.Append($"\n    .HasMaxLength({maxLength})");
                }

                if (column.Precision is { } precision)
                {
                    builder.Append($"\n    .HasPrecision({precision}, {column.Scale})");
                }

                builder.Append($"\n    .HasColumnType({CSharp.String(column.StoreType)})");
                builder.Append($"\n    .HasColumnName({CSharp.String(column.Name)})");
                if (column.DefaultSql is { } defaultSql)
                {
                    builder.Append($"\n    .HasDefaultValueSql({CSharp.String(defaultSql)})");
                }

                lines.Add(builder.Append(';').ToString());
            }

            lines.Add("b.HasKey(\"Id\");");
            foreach (var index in table.Indexes.OrderBy(index => index.Property, StringComparer.Ordinal))
            {
                lines.Add($"b.HasIndex({CSharp.String(index.Property)})" + (index.Unique ? "\n    .IsUnique()" : "") + $"\n    .HasDatabaseName({CSharp.String(index.Name)});");
            }

            lines.Add($"b.ToTable({CSharp.String(table.Name)}, (string)null);");
            blocks.Add(EntityBlock(table.TypeName, lines));
        }

        foreach (var table in tables.Where(table => table.ForeignKeys.Count > 0).OrderBy(table => table.TypeName, StringComparer.Ordinal))
        {
            var lines = table.ForeignKeys.OrderBy(key => key.Navigation, StringComparer.Ordinal).Select(key =>
                $"b.HasOne({CSharp.String(key.TargetType)}, {CSharp.String(key.Navigation)})\n" +
                $"    .WithMany()\n" +
                $"    .HasForeignKey({CSharp.String(key.Property)})\n" +
                $"    .OnDelete(DeleteBehavior.{key.OnDelete})" +
                (key.Required ? "\n    .IsRequired()" : "") +
                $"\n    .HasConstraintName({CSharp.String(key.Name)});").ToList();
            lines.AddRange(table.ForeignKeys.OrderBy(key => key.Navigation, StringComparer.Ordinal).Select(key => $"b.Navigation({CSharp.String(key.Navigation)});"));
            blocks.Add(EntityBlock(table.TypeName, lines));
        }

        var body = CSharp.Lines(CSharp.Separated(blocks), 12);
        return $"#pragma warning disable 612, 618\n{body}\n#pragma warning restore 612, 618";
    }

    private static string EntityBlock(string typeName, List<string> lines) =>
        $"modelBuilder.Entity({CSharp.String(typeName)}, b =>\n" +
        "    {\n" +
        CSharp.Lines(CSharp.Separated(lines), 8) + "\n" +
        "    });";

    /// <summary>C# keywords (reserved and contextual ones that can't name an anonymous-type member).</summary>
    private static readonly HashSet<string> Keywords = new(StringComparer.Ordinal)
    {
        "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char", "checked", "class", "const", "continue",
        "decimal", "default", "delegate", "do", "double", "else", "enum", "event", "explicit", "extern", "false", "finally",
        "fixed", "float", "for", "foreach", "goto", "if", "implicit", "in", "int", "interface", "internal", "is", "lock",
        "long", "namespace", "new", "null", "object", "operator", "out", "override", "params", "private", "protected",
        "public", "readonly", "ref", "return", "sbyte", "sealed", "short", "sizeof", "stackalloc", "static", "string",
        "struct", "switch", "this", "throw", "true", "try", "typeof", "uint", "ulong", "unchecked", "unsafe", "ushort",
        "using", "virtual", "void", "volatile", "while",
    };
}
