<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="Shouldly" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\CoreFoundry.Application\CoreFoundry.Application.csproj" />
    <ProjectReference Include="..\..\src\CoreFoundry.Domain\CoreFoundry.Domain.csproj" />
  </ItemGroup>

</Project>
